import type { Lang } from './types'

// Copy lifted from legacy language branches during localization migration.
const inlineCopy: Record<string, { id: string; en: string }> = {
  copy_hub_admin_dapat_melakukan_generate_55ecc8a: { id: "Hub Admin dapat melakukan generate video tanpa batas.", en: "Hub Admin can generate videos without limits." },
  copy_analisis_tersimpan_7a335c0: { id: "ANALISIS TERSIMPAN", en: "SAVED ANALYSES" },
  copy_kandidat_terbentuk_f5d0efc: { id: "KANDIDAT TERBENTUK", en: "CANDIDATES MADE" },
  copy_hub_admin_008c5c7: { id: "HUB ADMIN", en: "HUB ADMIN" },
  copy_kuota_tanpa_batas_50218ed: { id: "KUOTA TANPA BATAS", en: "UNLIMITED QUOTA" },
  copy_paket_aktif_4d6657e: { id: "PAKET AKTIF", en: "ACTIVE PLAN" },
  copy_retensi_file_51b9345: { id: "Retensi file", en: "File retention" },
  copy_hapus_otomatis_621380a: { id: "HAPUS OTOMATIS", en: "AUTO PURGE" },
  copy_ringkasan_132bd64: { id: "Ringkasan", en: "Summary" },
  copy_video_panjang_yang_diolah_menjadi__a64cb51: { id: "Video panjang yang diolah menjadi tiga klip vertikal.", en: "A long video transformed into three vertical clips." },
  copy_batas_84050af: { id: "Batas", en: "Limits" },
  copy_batas_paket_5e39719: { id: "BATAS PAKET", en: "PLAN LIMITS" },
  copy_per_video_1163a1c: { id: "per video", en: "per video" },
  copy_mnt_8458f97: { id: "MNT", en: "MIN" },
  copy_durasi_maks_04e338f: { id: "durasi maks", en: "max duration" },
  copy_jalan_pintas_a57c023: { id: "Jalan pintas", en: "Shortcuts" },
  copy_jalan_pintas_46b26d3: { id: "JALAN PINTAS", en: "SHORTCUTS" },
  copy_pilih_foto_jpg_png_atau_webp_6ae0054: { id: "Pilih foto JPG, PNG, atau WebP.", en: "Choose a JPG, PNG, or WebP image." },
  copy_ukuran_foto_maksimal_8_mb_716bed2: { id: "Ukuran foto maksimal 8 MB.", en: "Photo must be 8 MB or smaller." },
  copy_foto_profil_berhasil_diperbarui_54373be: { id: "Foto profil berhasil diperbarui.", en: "Profile photo updated." },
  copy_kuota_453abd3: { id: "Kuota", en: "Quota" },
  copy_kuota_harian_443f473: { id: "KUOTA HARIAN", en: "DAILY QUOTA" },
  copy_tanpa_batas_harian_41d0ef2: { id: "Tanpa batas harian", en: "No daily limit" },
  copy_akun_admin_dapat_menganalisis_dan__ff19923: { id: "Akun admin dapat menganalisis dan mengekspor tanpa kuota harian. Aktivitas tetap dicatat.", en: "Admin accounts can analyze and export without daily quotas. Activity is still recorded." },
  copy_peran_2299c98: { id: "Peran", en: "Role" },
  copy_sesi_6f6d566: { id: "Sesi", en: "Session" },
  copy_sesi_browser_memakai_cookie_httpon_f72154c: { id: "Sesi browser memakai cookie HttpOnly. Akun tersimpan di server ECLIPSE.", en: "Browser session uses an HttpOnly cookie. Accounts live on the ECLIPSE server." },
  copy_pengaturan_paket_gagal_dimuat_f1498f4: { id: "Pengaturan paket gagal dimuat.", en: "Plan settings could not be loaded." },
  copy_pengaturan_paket_gagal_disimpan_f5d7779: { id: "Pengaturan paket gagal disimpan.", en: "Plan settings could not be saved." },
  copy_ketentuan_paket_dbf59ca: { id: "Ketentuan paket", en: "Plan terms" },
  copy_nilai_ini_langsung_dipakai_sebagai_4d031f9: { id: "Nilai ini langsung dipakai sebagai kuota dan harga yang tampil di aplikasi.", en: "These values control enforced quotas and prices shown in the app." },
  copy_kelola_paket_akun_072ea66: { id: "Kelola paket akun", en: "Manage account plans" },
  copy_muat_ulang_da98d05: { id: "Muat ulang", en: "Refresh" },
  copy_pengaturan_langganan_tersimpan_dan_cedc53e: { id: "Pengaturan langganan tersimpan dan sudah berlaku.", en: "Subscription settings saved and applied." },
  copy_memuat_pengaturan_d6918f2: { id: "Memuat pengaturan…", en: "Loading settings…" },
  copy_akses_awal_setelah_pendaftaran_217a368: { id: "Akses awal setelah pendaftaran", en: "Starter access after registration" },
  copy_batch_video_per_hari_893c88b: { id: "Batch video per hari", en: "Video batches per day" },
  copy_masa_free_sejak_daftar_7b52de2: { id: "Masa Free sejak daftar", en: "Free period after signup" },
  copy_hari_133a711: { id: "hari", en: "days" },
  copy_analisis_per_hari_4dfa8f1: { id: "Analisis per hari", en: "Analyses per day" },
  copy_langganan_bulanan_ae1141e: { id: "Langganan bulanan", en: "Monthly subscription" },
  copy_batch_generate_per_hari_5f6d833: { id: "Batch generate per hari", en: "Generation batches per day" },
  copy_harga_per_bulan_28e1357: { id: "Harga per bulan", en: "Price per month" },
  copy_masa_aktif_efd0ab9: { id: "Masa aktif", en: "Active term" },
  copy_bulan_001e80f: { id: "bulan", en: "months" },
  copy_diskon_periode_promo_4b049a4: { id: "Diskon periode promo", en: "Campaign discount" },
  copy_promo_lite_mulai_5883c42: { id: "Promo Lite mulai", en: "Lite sale starts" },
  copy_promo_lite_berakhir_ea2afbf: { id: "Promo Lite berakhir", en: "Lite sale ends" },
  copy_jika_diskon_lebih_dari_0_isi_tangg_168d7ca: { id: "Jika diskon lebih dari 0%, isi tanggal mulai dan akhir promo. Atur 0% untuk menonaktifkan diskon.", en: "For discounts above 0%, set both campaign dates. Set to 0% to turn the discount off." },
  copy_promo_pro_mulai_be3a2dc: { id: "Promo Pro mulai", en: "Pro sale starts" },
  copy_promo_pro_berakhir_82baca1: { id: "Promo Pro berakhir", en: "Pro sale ends" },
  copy_tidak_ada_batas_kuota_paket_ini_me_5de8f00: { id: "Tidak ada batas kuota. Paket ini mengikuti role Hub Admin.", en: "No quota cap. This plan follows the Hub Admin role." },
  copy_perubahan_kuota_dan_harga_berlaku__f0a981a: { id: "Perubahan kuota dan harga berlaku segera. Perubahan masa Free langsung berlaku untuk akun Free; durasi Lite/Pro baru dipakai saat aktivasi atau perpanjangan berikutnya. Masa aktif Lite/Pro yang sudah berjalan tidak berubah. Pembayaran dicatat di luar aplikasi.", en: "Quota and price changes apply immediately. Free trial changes affect Free accounts right away; Lite/Pro terms apply to future assignments and renewals. Existing Lite/Pro expiry dates stay unchanged. Payments are handled outside the app." },
  copy_menyimpan_84f6256: { id: "Menyimpan…", en: "Saving…" },
  copy_simpan_perubahan_paket_e24730f: { id: "Simpan perubahan paket", en: "Save plan settings" },
  copy_kode_promo_gagal_dimuat_318ef6e: { id: "Kode promo gagal dimuat.", en: "Promo codes could not be loaded." },
  copy_kode_promo_berhasil_dibuat_ebeb55b: { id: "Kode promo berhasil dibuat.", en: "Promo code created." },
  copy_kode_promo_gagal_dibuat_74e1499: { id: "Kode promo gagal dibuat.", en: "Promo code could not be created." },
  copy_status_promo_gagal_diubah_843d154: { id: "Status promo gagal diubah.", en: "Could not update promo status." },
  copy_kode_promo_gagal_dihapus_724234b: { id: "Kode promo gagal dihapus.", en: "Could not delete promo code." },
  copy_tanpa_batas_waktu_9e150bf: { id: "Tanpa batas waktu", en: "No date limit" },
  copy_promo_06bc536: { id: "PROMO", en: "PROMOTIONS" },
  copy_kode_promo_1d6b7da: { id: "Kode promo", en: "Promo codes" },
  copy_buat_kode_diskon_terbatas_atur_pak_0bf042a: { id: "Buat kode diskon terbatas, atur paket, periode, dan jumlah pemakaian. Kode promo ditumpuk di atas diskon periode paket.", en: "Create time-limited codes, choose eligible plans, and cap usage. Codes stack on top of scheduled plan discounts." },
  copy_kode_promo_8620d13: { id: "Kode promo", en: "Promo code" },
  copy_untuk_paket_8f523e4: { id: "Untuk paket", en: "Applies to" },
  copy_lite_dan_pro_02def75: { id: "Lite dan Pro", en: "Lite and Pro" },
  copy_jenis_potongan_18ee103: { id: "Jenis potongan", en: "Discount type" },
  copy_persentase_990ca5b: { id: "Persentase", en: "Percentage" },
  copy_nominal_rupiah_46d5e00: { id: "Nominal Rupiah", en: "Fixed amount (IDR)" },
  copy_nilai_diskon_77d1715: { id: "Nilai diskon", en: "Discount value" },
  copy_mulai_opsional_e484b23: { id: "Mulai (opsional)", en: "Starts (optional)" },
  copy_berakhir_opsional_50dfa9f: { id: "Berakhir (opsional)", en: "Ends (optional)" },
  copy_maks_pemakaian_0_tanpa_batas_2888424: { id: "Maks. pemakaian (0 = tanpa batas)", en: "Max uses (0 = unlimited)" },
  copy_membuat_7827993: { id: "Membuat…", en: "Creating…" },
  copy_buat_kode_promo_86f2030: { id: "Buat kode promo", en: "Create promo code" },
  copy_memuat_kode_promo_dae48d3: { id: "Memuat kode promo…", en: "Loading promo codes…" },
  copy_belum_ada_kode_promo_2a3ba88: { id: "Belum ada kode promo.", en: "No promo codes yet." },
  copy_lite_pro_117c89c: { id: "Lite & Pro", en: "Lite & Pro" },
  copy_pemakaian_44ca085: { id: "pemakaian", en: "uses" },
  copy_aktif_703c7d8: { id: "Aktif", en: "Active" },
  copy_nonaktif_1d7d6c0: { id: "Nonaktif", en: "Inactive" },
  copy_nonaktifkan_8b9cb3c: { id: "Nonaktifkan", en: "Disable" },
  copy_aktifkan_a7f8fcc: { id: "Aktifkan", en: "Enable" },
  copy_hapus_7290f3b: { id: "Hapus", en: "Delete" },
  copy_qr_pembayaran_berhasil_diperbarui_8f554fb: { id: "QR pembayaran berhasil diperbarui.", en: "Payment QR updated." },
  copy_qr_gagal_diperbarui_6273560: { id: "QR gagal diperbarui.", en: "QR could not be updated." },
  copy_kode_qr_pembayaran_0e5d3ff: { id: "Kode QR pembayaran", en: "Payment QR code" },
  copy_qr_ini_ditampilkan_pada_checkout_s_d19f44e: { id: "QR ini ditampilkan pada checkout semua pelanggan. Unggah QRIS merchant yang aktif.", en: "This code appears at customer checkout. Upload an active merchant QRIS image." },
  copy_qris_pembayaran_saat_ini_6d45637: { id: "QRIS pembayaran saat ini", en: "Current payment QRIS" },
  copy_pilih_gambar_qris_f8efd6d: { id: "Pilih gambar QRIS", en: "Choose QRIS image" },
  copy_format_jpg_png_webp_maksimal_5_mb_efe0992: { id: "Format JPG, PNG, WebP · maksimal 5 MB.", en: "JPG, PNG, WebP · 5 MB maximum." },
  copy_mengunggah_34db028: { id: "Mengunggah…", en: "Uploading…" },
  copy_perbarui_qr_pembayaran_3a6e393: { id: "Perbarui QR pembayaran", en: "Update payment QR" },
  copy_daftar_pembayaran_gagal_dimuat_22aed03: { id: "Daftar pembayaran gagal dimuat.", en: "Payment list could not be loaded." },
  copy_bukti_pembayaran_ditolak_39d6ee2: { id: "Bukti pembayaran ditolak.", en: "Payment proof rejected." },
  copy_keputusan_pembayaran_gagal_disimpa_6c7fe27: { id: "Keputusan pembayaran gagal disimpan.", en: "Payment decision could not be saved." },
  copy_menunggu_pembayaran_82c41dc: { id: "Menunggu pembayaran", en: "Awaiting payment" },
  copy_perlu_ditinjau_45af867: { id: "Perlu ditinjau", en: "Needs review" },
  copy_disetujui_c20de56: { id: "Disetujui", en: "Approved" },
  copy_ditolak_03c608c: { id: "Ditolak", en: "Rejected" },
  copy_dibatalkan_dd218ec: { id: "Dibatalkan", en: "Cancelled" },
  copy_kedaluwarsa_430998f: { id: "Kedaluwarsa", en: "Expired" },
  copy_pembayaran_masuk_7040f45: { id: "PEMBAYARAN MASUK", en: "INCOMING PAYMENTS" },
  copy_verifikasi_langganan_b6cb892: { id: "Verifikasi langganan", en: "Subscription review" },
  copy_setujui_bukti_untuk_mengaktifkan_a_09f1a00: { id: "Setujui bukti untuk mengaktifkan atau memperpanjang paket akun.", en: "Approve a receipt to activate or renew the account plan." },
  copy_gagal_dimuat_130b237: { id: "Gagal dimuat", en: "Unavailable" },
  copy_perlu_ditinjau_d2ee16a: { id: "perlu ditinjau", en: "to review" },
  copy_memuat_transaksi_987cddd: { id: "Memuat transaksi…", en: "Loading payments…" },
  copy_belum_ada_pesanan_langganan_d8c1fd7: { id: "Belum ada pesanan langganan.", en: "No subscription orders yet." },
  copy_nominal_akhir_6237ad9: { id: "Nominal akhir", en: "Final amount" },
  copy_potongan_617761a: { id: "Potongan", en: "Discount" },
  copy_kode_unik_5ce57f3: { id: "Kode unik", en: "Unique code" },
  copy_id_transaksi_9eb9763: { id: "ID transaksi", en: "Transaction ID" },
  copy_dibuat_06abc1a: { id: "Dibuat", en: "Created" },
  copy_lihat_bukti_64b17c5: { id: "Lihat bukti", en: "View receipt" },
  copy_catatan_penolakan_opsional_4d8f7b1: { id: "Catatan penolakan (opsional)", en: "Rejection note (optional)" },
  copy_tolak_824ad24: { id: "Tolak", en: "Reject" },
  copy_setujui_aktifkan_a6a1782: { id: "Setujui & aktifkan", en: "Approve & activate" },
  copy_alasan_870171e: { id: "Alasan:", en: "Reason:" },
  copy_bukti_pembayaran_4f7baac: { id: "Bukti pembayaran", en: "Payment receipt" },
  copy_tutup_9b1d062: { id: "Tutup", en: "Close" },
  copy_bukti_transfer_pelanggan_e482045: { id: "Bukti transfer pelanggan", en: "Customer payment receipt" },
  copy_konfigurasi_server_tidak_dapat_dim_faf7146: { id: "Konfigurasi server tidak dapat dimuat. Pastikan backend ECLIPSE berjalan, lalu coba muat ulang.", en: "Server configuration could not be loaded. Make sure the ECLIPSE backend is running, then refresh." },
  copy_hapus_atau_nonaktifkan_akun_admin__3d4fe10: { id: "Hapus atau nonaktifkan akun admin aktif lain terlebih dahulu; minimal satu admin harus tetap aktif.", en: "Keep at least one active admin account; remove another admin from this selection first." },
  copy_ringkasan_admin_213e8b0: { id: "Ringkasan Admin", en: "Admin overview" },
  copy_status_data_dan_akun_pada_server_e_4b1c15b: { id: "Status data dan akun pada server ECLIPSE.", en: "Status of data and accounts on the ECLIPSE server." },
  copy_pengguna_role_ce5c0f9: { id: "Pengguna & Role", en: "Users & Roles" },
  copy_pengaturan_subscription_bcde249: { id: "Pengaturan Subscription", en: "Subscription settings" },
  copy_kelola_kuota_harga_dan_masa_aktif__4fd524b: { id: "Kelola kuota, harga, dan masa aktif semua paket akun.", en: "Manage quotas, prices, and active terms for every account plan." },
  copy_kelola_konfigurasi_provider_gemini_bdd8c29: { id: "Kelola konfigurasi provider Gemini.", en: "Manage Gemini provider configuration." },
  copy_kelola_jalur_koneksi_keluar_server_2435417: { id: "Kelola jalur koneksi keluar server untuk ingest media.", en: "Manage the server outbound route for media ingest." },
  copy_aktivitas_6a83bdd: { id: "Aktivitas", en: "Activity" },
  copy_tinjau_aktivitas_yang_tercatat_di__df0a3a9: { id: "Tinjau aktivitas yang tercatat di server.", en: "Review activity recorded by the server." },
  copy_pengaturan_sistem_39937ed: { id: "Pengaturan Sistem", en: "System settings" },
  copy_batas_aktif_dan_kemampuan_runtime__e3bd17c: { id: "Batas aktif dan kemampuan runtime server ECLIPSE.", en: "Active limits and runtime capabilities of the ECLIPSE server." },
  copy_server_eclipse_8a1231e: { id: "Server ECLIPSE", en: "ECLIPSE server" },
  copy_akun_pada_server_58b9fe3: { id: "Akun pada server", en: "Server accounts" },
  copy_aktivitas_tersimpan_di_server_c17a7f1: { id: "Aktivitas tersimpan di server", en: "Server activity records" },
  copy_metrik_job_dan_biaya_provider_belu_2eb4588: { id: "Metrik job dan biaya provider belum tersedia", en: "Job and provider cost metrics unavailable" },
  copy_cakupan_ringkasan_8826e58: { id: "Cakupan ringkasan", en: "Overview coverage" },
  copy_jumlah_akun_dan_aktivitas_dimuat_d_7b2286c: { id: "Jumlah akun dan aktivitas dimuat dari database server. Ringkasan job, biaya Gemini, dan statistik render belum disediakan oleh API.", en: "Account and activity counts are loaded from the server database. Job summaries, Gemini costs, and render statistics are not exposed by the API yet." },
  copy_status_akun_b3f830f: { id: "Status akun", en: "Account status" },
  copy_semua_status_1211fc1: { id: "Semua status", en: "All status" },
  copy_pilih_semua_akun_di_halaman_ini_3c39806: { id: "Pilih semua akun di halaman ini", en: "Select all accounts on this page" },
  copy_paket_ec463b5: { id: "Paket", en: "Plan" },
  copy_status_aba2332: { id: "Status", en: "Status" },
  copy_berakhir_a0af4d1: { id: "Berakhir: ", en: "Expires: " },
  copy_paket_akun_ee9dd28: { id: "Paket akun", en: "Account plan" },
  copy_paket_akun_diperbarui_be85eb4: { id: "Paket akun diperbarui.", en: "Account plan updated." },
  copy_paket_diperpanjang_sesuai_masa_akt_028eb03: { id: "Paket diperpanjang sesuai masa aktif yang diatur.", en: "Plan extended for its configured term." },
  copy_perpanjang_paket_9c17b54: { id: "Perpanjang paket", en: "Extend plan" },
  copy_tidak_ada_akun_yang_cocok_dengan_p_72d4b59: { id: "Tidak ada akun yang cocok dengan pencarian dan filter.", en: "No accounts match the current search and filters." },
  copy_halaman_daftar_akun_f3183a6: { id: "Halaman daftar akun", en: "User list pagination" },
  copy_sebelumnya_040e05e: { id: "Sebelumnya", en: "Previous" },
  copy_berikutnya_37371cd: { id: "Berikutnya", en: "Next" },
  copy_admin_dapat_mengatur_free_lite_dan_a64b7b9: { id: "Admin dapat mengatur Free, Lite, dan Pro untuk tiap akun. Kuota, harga, dan masa aktif diatur di Admin → Subscription. Pembayaran dicatat di luar aplikasi.", en: "Admins can assign Free, Lite, and Pro to accounts. Quotas, prices, and terms are configured under Admin → Subscription. Payments are handled outside the app." },
  copy_log_aktivitas_dihapus_5c18826: { id: "Log aktivitas dihapus.", en: "Activity log cleared." },
  copy_status_sistem_hanya_baca_18aefd5: { id: "STATUS SISTEM · HANYA BACA", en: "SYSTEM STATUS · READ ONLY" },
  copy_konfigurasi_operasional_91d21bf: { id: "Konfigurasi operasional", en: "Operational configuration" },
  copy_nilai_dimuat_langsung_dari_backend_8a7d0f8: { id: "Nilai dimuat langsung dari backend dan kemampuan FFmpeg pada server ini.", en: "Values are loaded from the backend and this server’s FFmpeg capabilities." },
  copy_memuat_12b6bfe: { id: "Memuat…", en: "Loading…" },
  copy_memuat_konfigurasi_server_8a2d484: { id: "Memuat konfigurasi server…", en: "Loading server configuration…" },
  copy_sumber_video_5168e81: { id: "SUMBER VIDEO", en: "VIDEO SOURCE" },
  copy_retensi_b661241: { id: "RETENSI", en: "RETENTION" },
  copy_jam_5fcffd1: { id: "jam", en: "hours" },
  copy_free_hari_8af2464: { id: "FREE / HARI", en: "FREE / DAY" },
  copy_analisis_afc724a: { id: "analisis", en: "analyses" },
  copy_bulan_46d675d: { id: "BULAN", en: "MONTH" },
  copy_batch_rp_9368d56: { id: "batch · Rp", en: "batches · Rp" },
  copy_tanpa_batas_generate_92a0d63: { id: "Tanpa batas generate", en: "Unlimited generation" },
  copy_format_ekspor_7910236: { id: "FORMAT EKSPOR", en: "EXPORT FORMAT" },
  copy_render_server_fe528dd: { id: "RENDER SERVER", en: "SERVER RENDERING" },
  copy_encoder_ffmpeg_yang_terdeteksi_65b3b9d: { id: "Encoder FFmpeg yang terdeteksi", en: "Detected FFmpeg encoders" },
  copy_tersedia_649f655: { id: "tersedia", en: "available" },
  copy_tidak_ada_856bde7: { id: "tidak ada", en: "unavailable" },
  copy_direkomendasikan_9fa5ab5: { id: "Direkomendasikan", en: "Recommended" },
  copy_ai_focus_framing_wajah_orang_245ba26: { id: "AI Focus Framing (wajah + orang)", en: "AI Focus Framing (face + person)" },
  copy_tidak_tersedia_b604bbf: { id: "tidak tersedia", en: "unavailable" },
  copy_fallback_gerakan_1c68616: { id: "Fallback gerakan", en: "Motion fallback" },
  copy_layanan_api_cec1f51: { id: "LAYANAN API", en: "API SERVICE" },
  copy_berjalan_e101b62: { id: "Berjalan", en: "Online" },
  copy_versi_bc33ded: { id: "Versi", en: "Version" },
  copy_penghapusan_permanen_menghapus_aku_8f2d413: { id: "Penghapusan permanen menghapus akun, sesi, job, file media, dan catatan token Gemini milik akun ini. Catatan audit administratif disimpan sampai masa retensinya berakhir.", en: "Permanent deletion removes this account, sessions, jobs, media files, and its Gemini token records. Administrative audit entries remain until their retention period ends." },
  copy_menghapus_1ec66c0: { id: "Menghapus…", en: "Deleting…" },
  copy_ini_menghapus_permanen_akun_sesi_j_71aec76: { id: "Ini menghapus permanen akun, sesi, job, file media, dan catatan token Gemini untuk akun terpilih. Catatan audit administratif tetap disimpan sampai masa retensinya berakhir.", en: "This permanently deletes the selected accounts, sessions, jobs, media files, and Gemini token records. Administrative audit entries remain until their retention period ends." },
  copy_nonaktifkan_akun_ab1a87b: { id: "Nonaktifkan akun", en: "Disable account" },
  copy_aktifkan_akun_68d47b4: { id: "Aktifkan akun", en: "Enable account" },
  copy_akun_akan_langsung_kehilangan_akse_9a02265: { id: "Akun akan langsung kehilangan akses dan seluruh sesi browser-nya dicabut. Job dan riwayat tetap tersimpan.", en: "The account immediately loses access and all browser sessions are revoked. Jobs and history are retained." },
  copy_akun_dapat_masuk_kembali_riwayat_d_8a91f9f: { id: "Akun dapat masuk kembali. Riwayat dan job sebelumnya tetap tersedia sesuai retensi.", en: "The account can sign in again. Existing jobs and history remain subject to retention." },
  copy_pembuka_1968d77: { id: "Pembuka", en: "Opening" },
  copy_kreator_indonesia_membuka_video_de_639eeda: { id: "Kreator Indonesia membuka video dengan gestur antusias.", en: "Indonesian creator opens the video with an energetic gesture." },
  copy_momen_lucu_cbb5ddc: { id: "Momen lucu", en: "Punchline" },
  copy_kreator_indonesia_tertawa_saat_men_64d847e: { id: "Kreator Indonesia tertawa saat menyampaikan bagian lucu.", en: "Indonesian creator laughs during a funny moment." },
  copy_konteks_b3289a6: { id: "Konteks", en: "Context" },
  copy_kreator_indonesia_menjelaskan_kont_fbc5e65: { id: "Kreator Indonesia menjelaskan konteks dengan ekspresi fokus.", en: "Indonesian creator explains the context with a focused expression." },
  copy_beranda_fdb349e: { id: "Beranda", en: "Home" },
  copy_tentang_4fd3875: { id: "Tentang", en: "About" },
  copy_produk_73fc2b5: { id: "Produk", en: "Product" },
  copy_fitur_62b3439: { id: "Fitur", en: "Features" },
  copy_cara_kerja_a99b66d: { id: "Cara kerja", en: "How it works" },
  copy_contoh_hasil_1da2e58: { id: "Contoh hasil", en: "Examples" },
  copy_coba_gratis_c3d786a: { id: "Coba gratis", en: "Get started free" },
  copy_lihat_hasilnya_b05b2d6: { id: "Lihat hasilnya ↓", en: "See the output ↓" },
  copy_60_menit_7b30081: { id: "60 MENIT", en: "60 MIN" },
  copy_hapus_otomatis_24_jam_7628c36: { id: "HAPUS OTOMATIS · 24 JAM", en: "AUTO DELETE · 24H" },
  copy_00_00_sumber_05aa546: { id: "00:00 SUMBER", en: "00:00 SOURCE" },
  copy_00_42_skor_49d5b8f: { id: "00:42 SKOR", en: "00:42 SCORE" },
  copy_02_05_ekspor_2700ece: { id: "02:05 EKSPOR", en: "02:05 EXPORT" },
  copy_tampilan_editor_video_eclipse_yang_2ec1d9c: { id: "Tampilan editor video Eclipse yang sedang digunakan di ponsel", en: "Eclipse video editor open on a phone, mid-edit" },
  copy_cara_kerja_7b8157b: { id: "CARA KERJA", en: "HOW IT WORKS" },
  copy_dari_video_panjang_menjadi_klip_3cabdf1: { id: "Dari video panjang menjadi klip.", en: "From long videos to short clips." },
  copy_hasil_162555f: { id: "HASIL", en: "OUTPUT" },
  copy_video_58_menit_3_klip_vertikal_6721a2a: { id: "Video 58 menit. 3 klip vertikal.", en: "58-minute source. Three vertical clips." },
  copy_tinjau_skor_durasi_dan_waktu_mulai_3218955: { id: "Tinjau skor, durasi, dan waktu mulai setiap kandidat sebelum memilih klip.", en: "Review each candidate’s score, duration, and start time before choosing clips." },
  copy_16_9_video_sumber_cb97a34: { id: "16:9 — VIDEO SUMBER", en: "16:9 — SOURCE VIDEO" },
  copy_kreator_indonesia_sedang_merekam_p_ac301fa: { id: "Kreator Indonesia sedang merekam podcast sebagai video sumber.", en: "Indonesian creator recording a podcast as the source video." },
  copy_transkrip_skor_per_menit_a1c0254: { id: "transkrip + skor per menit", en: "transcript + per-minute scores" },
  copy_video_klip_a7c4a82: { id: "VIDEO → KLIP", en: "VIDEO → CLIPS" },
  copy_pilih_momen_atur_potongan_lalu_sia_71ec956: { id: "Pilih momen, atur potongan, lalu siapkan beberapa klip sekaligus.", en: "Choose moments, adjust the cuts, and prepare several clips at once." },
  copy_pembuka_6a54aab: { id: "pembuka", en: "opening" },
  copy_momen_lucu_71ddb77: { id: "momen lucu", en: "punchline" },
  copy_konteks_ba53778: { id: "konteks", en: "context" },
  copy_skor_klip_merupakan_perkiraan_ai_b_e88ba71: { id: "Skor klip merupakan perkiraan AI berdasarkan video dan transkrip. Skor membantu proses penyuntingan, tetapi tidak menjamin performa.", en: "Clip scores are AI estimates based on the video and transcript. They can guide editing, but do not predict performance." },
  copy_subtitle_aktif_f4e5da6: { id: "SUBTITLE ▸ AKTIF", en: "SUBTITLES ▸ ON" },
  copy_5_klip_d4251c0: { id: "×5 KLIP", en: "×5 CLIPS" },
  copy_mulai_dengan_paket_gratis_9adab27: { id: "Mulai dengan paket gratis.", en: "Start with the free plan." },
  copy_aktivasi_dibantu_hub_admin_eb9c85c: { id: "Aktivasi dibantu Hub Admin", en: "Activated by a Hub Admin" },
  copy_kuota_tanpa_batas_untuk_akun_denga_c95342e: { id: "Kuota tanpa batas untuk akun dengan peran Hub Admin.", en: "Unlimited quota for accounts with the Hub Admin role." },
  copy_tanpa_batas_batch_generate_harian_62f8708: { id: "Tanpa batas batch generate harian", en: "No daily generation batch limit" },
  copy_akses_berdasarkan_peran_hub_admin_3b68af8: { id: "Akses berdasarkan peran Hub Admin", en: "Access granted by the Hub Admin role" },
  copy_hubungi_admin_5408e84: { id: "Hubungi Admin", en: "Contact Admin" },
  copy_mulai_gratis_73e295b: { id: "MULAI GRATIS", en: "GET STARTED" },
  copy_siap_membuat_klip_pertama_0adaf48: { id: "Siap membuat klip pertama?", en: "Ready to make your first clip?" },
  copy_buat_akun_gratis_unggah_video_lalu_10aed01: { id: "Buat akun gratis, unggah video, lalu pilih momen yang ingin dijadikan klip.", en: "Create a free account, upload a video, and choose the moments you want to turn into clips." },
  copy_file_dihapus_otomatis_dalam_24_jam_bd7db0b: { id: "FILE DIHAPUS OTOMATIS DALAM 24 JAM", en: "FILES AUTO-DELETE WITHIN 24 HOURS" },
  copy_punya_pertanyaan_baca_jawaban_di_b_88bbb78: { id: "Punya pertanyaan? Baca jawaban di bawah atau coba Studio.", en: "Have a question? Read the answers below or try the Studio." },
  copy_video_panjang_klip_vertikal_64b3c20: { id: "VIDEO PANJANG → KLIP VERTIKAL", en: "LONG VIDEOS → VERTICAL CLIPS" },
  copy_bantuan_0ca29a5: { id: "Bantuan", en: "Help" },
  copy_pilih_dan_siapkan_klip_dari_video__c344ccc: { id: "Pilih dan siapkan klip dari video panjang.", en: "Select and prepare clips from long videos." },
  copy_gratis_bd4ffb5: { id: "Gratis", en: "Free" },
  copy_khusus_hub_admin_806a185: { id: "Khusus Hub Admin", en: "Hub Admin only" },
  copy_tanpa_batas_kuota_bca1285: { id: "Tanpa batas kuota", en: "No quota limit" },
  copy_pesanan_pembayaran_gagal_dibuat_c544d69: { id: "Pesanan pembayaran gagal dibuat.", en: "Could not create payment order." },
  copy_batch_generate_per_hari_9974f90: { id: "batch generate per hari", en: "generation batches per day" },
  copy_perlu_upgrade_5f1db35: { id: "Perlu upgrade", en: "Upgrade needed" },
  copy_pilih_kuota_yang_sesuai_d0e030b: { id: "Pilih kuota yang sesuai", en: "Choose the quota that fits" },
  copy_paket_aktif_5571bf6: { id: "Paket aktif", en: "Current plan" },
  copy_batch_generate_hari_1117d0b: { id: "batch generate / hari", en: "generation batches / day" },
  copy_promo_2aa0cce: { id: "PROMO", en: "SALE" },
  copy_pembayaran_belum_selesai_4a2adb4: { id: "Pembayaran belum selesai", en: "Payment not completed" },
  copy_bukti_menunggu_verifikasi_c886c46: { id: "Bukti menunggu verifikasi", en: "Proof awaiting review" },
  copy_langganan_aktif_1ceb2dd: { id: "Langganan aktif", en: "Subscription active" },
  copy_pembayaran_ditolak_3cd6b9e: { id: "Pembayaran ditolak", en: "Payment rejected" },
  copy_buat_pesanan_baru_untuk_mencoba_ke_d7c5162: { id: "Buat pesanan baru untuk mencoba kembali.", en: "Create a new order to try again." },
  copy_lihat_pembayaran_0e9aa39: { id: "Lihat pembayaran", en: "View payment" },
  copy_pembayaran_melalui_qris_diverifika_de40a22: { id: "Pembayaran melalui QRIS diverifikasi Hub Admin sebelum paket diaktifkan.", en: "QRIS payments are reviewed by a Hub Admin before the plan is activated." },
  copy_fitur_b8a4208: { id: "FITUR", en: "FEATURES" },
  copy_analisis_diproses_oleh_server_ecli_c765da6: { id: "Analisis diproses oleh server ECLIPSE.", en: "Analysis is processed by the ECLIPSE server." },
  copy_gagal_memuat_pool_proxy_ff930f9: { id: "Gagal memuat pool proxy.", en: "Could not load the proxy pool." },
  copy_proxy_disimpan_terenkripsi_di_serv_81d92bf: { id: "Proxy disimpan terenkripsi di server dan ditambahkan ke pool.", en: "Proxy was encrypted on the server and added to the pool." },
  copy_gagal_menambahkan_proxy_9025491: { id: "Gagal menambahkan proxy.", en: "Could not add proxy." },
  copy_gagal_memperbarui_proxy_0ba6678: { id: "Gagal memperbarui proxy.", en: "Could not update proxy." },
  copy_pemeriksaan_proxy_gagal_a34f9c2: { id: "Pemeriksaan proxy gagal.", en: "Proxy check failed." },
  copy_gagal_menghapus_proxy_111f71e: { id: "Gagal menghapus proxy.", en: "Could not remove proxy." },
  copy_nonaktif_3dbd84d: { id: "Nonaktif", en: "Disabled" },
  copy_cooldown_893b92f: { id: "Cooldown", en: "Cooling down" },
  copy_sehat_3879846: { id: "Sehat", en: "Healthy" },
  copy_perlu_diperiksa_7206bdb: { id: "Perlu diperiksa", en: "Needs attention" },
  copy_belum_diuji_90030b8: { id: "Belum diuji", en: "Not tested" },
  copy_pool_egress_rahasia_server_89bbf14: { id: "POOL EGRESS · RAHASIA SERVER", en: "EGRESS POOL · SERVER SECRETS" },
  copy_tambahkan_proxy_sebanyak_yang_dipe_7a4a49a: { id: "Tambahkan proxy sebanyak yang diperlukan. Pemilihan endpoint dibagi antarakun; tiap akun mempertahankan proxy yang sama untuk seluruh job agar alamat egress stabil.", en: "Add as many proxies as needed. Endpoints are distributed across accounts; each account keeps the same proxy across jobs for stable egress." },
  copy_aktif_ad949a8: { id: "aktif", en: "active" },
  copy_fallback_environment_ec79d98: { id: "Fallback environment", en: "Environment fallback" },
  copy_sedang_digunakan_karena_belum_ada__99d8100: { id: "Sedang digunakan karena belum ada proxy admin yang terdaftar.", en: "Active because no admin proxies are registered." },
  copy_dipakai_jika_pool_admin_dihapus_se_bd1220e: { id: "Dipakai jika pool admin dihapus seluruhnya.", en: "Used if the admin pool is completely removed." },
  copy_nama_proxy_7323030: { id: "Nama proxy", en: "Proxy name" },
  copy_contoh_egress_asia_01_b4f0e32: { id: "Contoh: Egress Asia 01", en: "Example: Asia egress 01" },
  copy_url_proxy_6e5b827: { id: "URL proxy", en: "Proxy URL" },
  copy_sembunyikan_ca01fef: { id: "Sembunyikan", en: "Hide" },
  copy_tampilkan_b649d8a: { id: "Tampilkan", en: "Show" },
  copy_tambah_proxy_1fff4c3: { id: "Tambah proxy", en: "Add proxy" },
  copy_mendukung_http_https_kredensial_di_40fc13a: { id: "Mendukung HTTP/HTTPS. Kredensial dienkripsi di server. Kegagalan proxy akan membuat endpoint cooldown dan job mencoba endpoint sehat lain.", en: "HTTP/HTTPS supported. Credentials are encrypted on the server. Failed endpoints cool down and jobs retry another healthy endpoint." },
  copy_daftar_proxy_9c8de93: { id: "Daftar proxy", en: "Proxy list" },
  copy_kegagalan_beruntun_1ed6062: { id: "Kegagalan beruntun", en: "Consecutive failures" },
  copy_prioritas_ff1aa0c: { id: "Prioritas", en: "Priority" },
  copy_terakhir_diuji_6ea6912: { id: "Terakhir diuji", en: "Last checked" },
  copy_ip_keluar_5e5d203: { id: "IP keluar", en: "Egress IP" },
  copy_aktif_kembali_f4476db: { id: "Aktif kembali", en: "Available again" },
  copy_memeriksa_aebc44d: { id: "Memeriksa…", en: "Checking…" },
  copy_uji_egress_859729e: { id: "Uji egress", en: "Test egress" },
  copy_aktif_d4476e1: { id: "Aktif", en: "Enabled" },
  copy_hapus_7bd98ef: { id: "Hapus", en: "Remove" },
  copy_proxy_environment_aktif_7f6b172: { id: "Proxy environment aktif", en: "Environment proxy active" },
  copy_pool_proxy_masih_kosong_83d68dd: { id: "Pool proxy masih kosong", en: "Proxy pool is empty" },
  copy_endpoint_environment_digunakan_seb_1a5b8fc: { id: "Endpoint environment digunakan sebagai fallback tunggal. Tambahkan proxy di atas untuk mulai membangun pool dan rotasi antarakun.", en: "The environment endpoint is used as a single fallback. Add proxies above to build a pool and distribute accounts." },
  copy_tambahkan_beberapa_endpoint_untuk__37b4c75: { id: "Tambahkan beberapa endpoint untuk membagi pemakaian dan mengaktifkan failover otomatis.", en: "Add multiple endpoints to distribute usage and enable automatic failover." },
  copy_proxy_dipertahankan_per_akun_dan_p_ee3e4ad: { id: "Proxy dipertahankan per akun dan per job. Jika endpoint gagal, job mencoba hingga dua endpoint lain; akun dapat berpindah egress IP dan cookie YouTube mungkin perlu diperbarui. Uji koneksi memeriksa IP keluar server.", en: "Proxies are sticky per account and job. If an endpoint fails, a job tries up to two alternatives; the account may change egress IP and YouTube cookies might need refreshing. Connectivity checks show the server egress IP." },
  copy_api_key_disimpan_terenkripsi_di_se_782456a: { id: "API key disimpan terenkripsi di server.", en: "API key was encrypted and saved on the server." },
  copy_hapus_api_key_94b05a5: { id: "Hapus API key", en: "Delete API key" },
  copy_api_key_dihapus_17acf97: { id: "API key dihapus.", en: "API key deleted." },
  copy_kredensial_server_d962b64: { id: "Kredensial server.", en: "Server-side credentials." },
  copy_api_key_disimpan_terenkripsi_di_se_83b2a3e: { id: "API key disimpan terenkripsi di server dan tidak dikirim kembali ke browser. Pemakaian dibagi bergilir berdasarkan Google project, karena kuota Gemini berlaku pada level project; beberapa key dalam project yang sama bukan kuota terpisah.", en: "API keys are encrypted on the server. Requests rotate across Google projects because Gemini quotas apply at project level; multiple keys in one project do not create separate quota pools." },
  copy_pemakaian_token_dari_respons_gemin_b1449a5: { id: "Pemakaian token dari respons Gemini dicatat per project/model. Angka USD belum tersedia dan batas $50/bulan maupun peringatan 80% belum ditegakkan; cocokkan biaya aktual dengan Google Cloud Billing.", en: "Gemini response token usage is recorded by project/model. USD spend is unavailable and the $50/month cap and 80% alert are not enforced; reconcile actual charges with Google Cloud Billing." },
  copy_pool_api_gemini_6800733: { id: "Pool API Gemini", en: "Gemini API pool" },
  copy_tambah_api_22bc8ef: { id: "Tambah API", en: "Add API" },
  copy_tambah_kredensial_gemini_82ef511: { id: "Tambah kredensial Gemini", en: "Add Gemini credentials" },
  copy_nama_alias_a4556a2: { id: "Nama/alias", en: "Name/alias" },
  copy_batal_ad558c5: { id: "Batal", en: "Cancel" },
  copy_simpan_key_ce28c12: { id: "Simpan key", en: "Save key" },
  copy_nama_6551fec: { id: "Nama", en: "Name" },
  copy_urutan_a96401f: { id: "Urutan", en: "Priority" },
  copy_aksi_944b421: { id: "Aksi", en: "Actions" },
  copy_key_tidak_valid_4734f1d: { id: "Key tidak valid", en: "Invalid key" },
  copy_terhubung_17658ce: { id: "Terhubung", en: "Connected" },
  copy_error_5a4f95b: { id: "Error", en: "Error" },
  copy_tes_5e4455b: { id: "Tes", en: "Test" },
  copy_belum_ada_api_key_tambahkan_key_ag_83e1c3c: { id: "Belum ada API key. Tambahkan key agar analisis dapat dijalankan.", en: "No API keys yet. Add one to enable analysis." },
  copy_pemakaian_gemini_30_hari_5058bd7: { id: "Pemakaian Gemini · 30 hari", en: "Gemini usage · 30 days" },
  copy_token_aktual_yang_dilaporkan_api_b_232c0cb: { id: "Token aktual yang dilaporkan API; bukan tagihan USD.", en: "Provider-reported token counts; not USD billing." },
  copy_panggilan_dicatat_595b231: { id: "Panggilan dicatat", en: "Recorded calls" },
  copy_respons_sukses_f6abf2a: { id: "Respons sukses", en: "Successful responses" },
  copy_respons_gagal_40c26e5: { id: "Respons gagal", en: "Failed responses" },
  copy_token_input_fbb2f67: { id: "Token input", en: "Input tokens" },
  copy_token_output_e4240a3: { id: "Token output", en: "Output tokens" },
  copy_respons_tanpa_usage_6d290ac: { id: "Respons tanpa usage", en: "Responses without usage" },
  copy_project_659bd73: { id: "Project", en: "Project" },
  copy_model_855d5a7: { id: "Model", en: "Model" },
  copy_panggilan_440ff1a: { id: "Panggilan", en: "Calls" },
  copy_input_token_f192a15: { id: "Input token", en: "Input tokens" },
  copy_output_token_f3dc7b5: { id: "Output token", en: "Output tokens" },
  copy_total_token_5349357: { id: "Total token", en: "Total tokens" },
  copy_belum_ada_panggilan_gemini_tercata_616e3cf: { id: "Belum ada panggilan Gemini tercatat pada periode ini.", en: "No Gemini calls recorded in this period." },
  copy_pemakaian_per_pengguna_19fb284: { id: "Pemakaian per pengguna", en: "Usage by user" },
  copy_pengguna_9fb0dcf: { id: "Pengguna", en: "User" },
  copy_tanpa_usage_e5d89d3: { id: "Tanpa usage", en: "Usage unknown" },
  copy_rincian_per_job_1b34771: { id: "Rincian per job", en: "Usage by job" },
  copy_pencatatan_dimulai_setelah_pembaru_5e26913: { id: "Pencatatan dimulai setelah pembaruan ini. Angka yang tidak disertakan provider tetap ditandai tidak diketahui. Belum ada estimasi biaya maupun pemblokiran otomatis saat batas bulanan tercapai.", en: "Tracking starts after this update. Counters omitted by the provider remain unknown. Cost estimation and automatic blocking at the monthly limit are not implemented yet." },
  copy_perilaku_failover_508e51a: { id: "Perilaku failover", en: "Failover behavior" },
  copy_jika_model_pilihan_gagal_atau_kuot_6357cfa: { id: "Jika model pilihan gagal atau kuotanya penuh, server mencoba model Flash lain yang tersedia untuk key itu, lalu beralih ke key aktif berikutnya.", en: "If the selected model fails or reaches quota, the server tries other Flash models available to that key, then moves to the next enabled key." },
  copy_key_dari_project_yang_sama_bisa_be_3509947: { id: "Key dari project yang sama bisa berbagi kuota Google Cloud.", en: "Keys from the same Google project may share Google Cloud quota." },
  copy_key_mentah_tidak_ditampilkan_kemba_e6d3a1f: { id: "Key mentah tidak ditampilkan kembali setelah disimpan.", en: "Raw keys are never shown again after saving." },
  copy_notifikasi_gagal_dimuat_f1599ea: { id: "Notifikasi gagal dimuat.", en: "Notifications could not be loaded." },
  copy_pemberitahuan_akun_9e7023d: { id: "Pemberitahuan akun", en: "Account notifications" },
  copy_pusat_notifikasi_c571165: { id: "PUSAT NOTIFIKASI", en: "NOTIFICATION CENTER" },
  copy_pemberitahuan_8848b62: { id: "Pemberitahuan", en: "Notifications" },
  copy_tandai_semua_dibaca_92c80f3: { id: "Tandai semua dibaca", en: "Mark all read" },
  copy_coba_lagi_f7ed4b5: { id: "Coba lagi", en: "Retry" },
  copy_belum_ada_pemberitahuan_7df072f: { id: "Belum ada pemberitahuan.", en: "You’re all caught up." },
  copy_proxy_egress_b7596d1: { id: "Proxy / Egress", en: "Proxy / Egress" },
}

export function getInlineCopy(language: Lang | boolean, key: string): string {
  const lang = typeof language === 'boolean' ? (language ? 'id' : 'en') : language
  return inlineCopy[key]?.[lang] ?? ''
}
